### ISSUE TITLE
初期位置の修正

### ISSUE THREAD

**Issue by Atria64** [hakodatemapp/Android_since_2019#1]
タイトル画面から地図画面に遷移したときに初期位置が自分の位置になっていない不具合。

**Comment by Yuritani2000** [comment]
初期位置の現在地表示が一応できたので、仮版としてpushします。後ほど整理したものを再度pushします。
・Location型のmyLocateを使用
・緯度経度の変数を別に宣言、同時に函館駅前の座標で初期化
・GPSから取得し緯度経度を上書き
　→myLocateがnullだったらネットワークから取得し緯度経度を上書き
　→myLocateがnullだったら函館駅前の座標のまま表示という流れ
・位置情報OFFの場合のダイアログの表示は、既存のものを流用
・Android 6.0の実機（Sony Xperia Z5）にて動作を確認
注：これは動作確認後の仮バージョンです。パーミッション確認の実装を初心者ながらやってみようとコードのあちこちをごにょごにょいじっています。
今回の修正で必要となるのは80行目,81行目に行われている変数の初期化と、439行目～470行目までのlocationStart()メソッド、285行目の座標指定部分です。
後ほどコードを整理して再度pushします。
ちなみに、パーミッション確認時の問題は、アプリに位置情報の権限が与えられていなくても、権限の確認を行うif文（404行目）がうまく働かずに位置情報が許可されているかのようにふるまってしまうことだと考えられます。（405行目のLogが表示されない）

**Comment by Yuritani2000** [comment]
初期位置の表示ができるようになったものです。前回の仮版から不要なコードやコメントアウトを削除しています。
・LocationがたmyLocateを使用
・onCreateから呼び出される（130行目）locationStartメソッド（389～415行目）を定義し、その中で初期の緯度経度を取得
・緯度経度を表す変数（latitude及びlongitude）をフィールドとして新しく宣言（80，81行目）。同時に函館駅前の座標で初期化。
・Location型のmyLocateをlocationStartで宣言すると同時に、GPSからの位置情報取得。
　→myLocateがnullだったらインターネットから位置情報取得
　→いずれかから位置情報が取得できた状態（myLocate != null）ならば初期位置を更新
　　できなければ緯度経度は初期化時の函館駅前の座標から上書きされない
・GPSがOFFになっている場合はGPSの有効化を促すダイアログを表示（714～732行目にある既存のものを使用）
・初期位置の座標の指定は、函館駅前の座標を渡すのではなく前述の緯度経度の変数（220行目）を使用
・Android 4.0.4 (API 15), Android 5.0.2 (おそらくAPI 21), Android 6.0 (API 23), Android 9 (API 28)の実機にて動作を確認
・

※現在の問題点
・GPSがOFF時ピン選択画面から海抜表示をONにして地図画面に戻る際、GPSの有効化を促すダイアログが2重に表示される
・初期位置の位置情報をインターネットからとっているかGPSからとっているか明確でない。
（・Android 4.0.4の実機（SONY Walkman NW-F805）は画面のサイズが著しく小さいためか、ピン選択時のチェックボックスが表示されず）
・API23以降に対応するためパーミッション許可の処理を記述しようとした（126～131行目及び344行目～385行目）が、API 23とAPI 28の実機において権限が与えられていないにもかかわらず権限許可のダイアログが表示されないため、パーミッション許可にかかわる部分はコメントアウトした。これによりパーミッション許可は行われず直接位置情報の取得へ進むようになっている。
・パーミッション許可の処理を書くに伴い、526～552行目のgetAltitude()メソッドは、mLocationManagerがインスタンス化された（パーミッション許可が通った）場合とそうでない場合で処理を変えるようにした。ここはコメントアウトは行っていない。

**Comment by Yuritani2000** [comment]
#20 でcloseします。
