### ISSUE TITLE
[周辺の地図を表示する]ボタンを押下時クラッシュする不具合

### ISSUE THREAD

**Issue by Atria64** [hakodatemapp/Android_since_2019#10]
**現在確認しているバグ**
GPSの使用権限を取得できていないがために、[周辺の地図を表示する]ボタンを押下時クラッシュする不具合

**バグの再現性**
APIレベル29にて発生を確認。再現性も確認できている。
Google Play Storeからダウンロードするものは対象外(これは自動的にダウングレードされた状態で実行されるため [要出典])

**テスト条件**
GPSを取得する際に SecurityException が出力されないこと。

**当核エラー**
![image](https://user-images.githubusercontent.com/49768768/66297610-fb911b80-e92a-11e9-984f-906789ca2b16.png)

**その他注意事項**
> 特筆すべきことがあればここに書く

AndroidAPIレベルによる場合分けが必要と思われる。
APIレベル23以降で起こると思われる。[要出典]

**Comment by Atria64** [comment]
APIレベル23での動作を確認しました。

**Comment by Atria64** [comment]
APIレベル28での **バグの発生** を確認しました。

**Comment by Yuritani2000** [comment]
#20 でcloseします。
