### ISSUE TITLE
GPS

### ISSUE THREAD

**Issue by Yuritani2000** [hakodatemapp/Android_since_2019#16]
**作ろうとしている機能の詳細**
> 具体的にどのような機能？何を目的に実装する？  

[例：検索機能を実装するステップの１つ。このタスクでは検索時に使用する入力フォームを作成して、入力したデータを取得することが目的。]  

**テスト条件**
> 完成の定義をかく。どんなテストをクリアすればこのタスクを完了とみなせるのかを書く。前期とは違って実際にコードを書いているので、条件を満たすテストも行う。(できれば…)  

1. [入力フォームをタッチしたときにキーボードがでる]  
1. [入力をキャンセルした場合入力値がリセットされる]  
1. [入力文字は日本語・英語を許可できている]  
1. [入力した値をString型で返り値として取得している]  
1. [30文字以上の入力は拒否する]  

**見積もり**
> どのくらいでタスクが終わるかを見積もったものを書く。単位は(m/人 = 1人でやってなん分かかるか) 
 
[60 m/人]  

**その他注意事項**
> 特筆すべきことがあればここに書く  

[developからdevelop/searchブランチを切って作業をします。]  

****タスク作成者への注意事項****
1. タグ管理をしっかりやってほしいです。上のタスクを例にとると："優先度B", "feat(or 機能)", "search(or 検索)", "form(or 入力フォーム)"くらいは最低限つけてほしい。  
2. このカードの存在を忘れないで(T . T)  
    作ったタスクは移動すべきタイミングでカラムを移動し、最後まで見守りましょう。

**Comment by Atria64** [comment]
#17 に移動するためcloseとのこと
